db:
  build: psql_docker
  environment: 
    - POSTGRES_PASSWORD=$$(PSQL_DATABASE_PASSWORD)
    - POSTGRES_DB=$$(PSQL_DATABASE_NAME)
    - POSTGRES_USER=$$(PSQL_DATABASE_USER)
  volumes:
    - ./entry-point.sh:/docker-entrypoint-initdb.d/entry-point.sh
    - ./get_env.awk:/docker-entrypoint-initdb.d/get_env.awk
backend:
  build: .
  env_file: 
    - ./manga_reader/config/.env
  ports: 
    - 8000:8000
  links: 
    - db
