version: '3.7'

services:
  backend:
    build: .
    # Collect env variables from this file and set them in container
    env_file:
      - .envs/dev.env
    command: bash -c "source /venv/bin/activate &&
                      celery -A manga_reader.celery.app worker -n manga@%h
                      --loglevel=INFO -B"
    environment:
      - PORT=8000
    ports:
      - 5500:8000
    # wait until 'db' process starts and then run
    depends_on:
      - db
      - redis

  db:
    image: postgres:12
    # Persist container's '/var/lib/postgresql/data/' in volume named 'sora_postgres'
    volumes:
      - sora_postgres:/var/lib/postgresql/data/
    ports:
      # Allow connecting to container db from localhost:5433
      - 5502:5432
    env_file:
      - .envs/dev.env
  
  redis:
    image: "redis:alpine"
    # launch redis server
    command: redis-server
    expose:
      - "6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  # sora_postgres volume (docker will handle local path)
  sora_postgres: