version: '3.7'

services:
  backend:
    build: .
    # Collect env variables from this file and set them in container
    env_file:
      - .envs/dev.env
    environment:
      - PORT=8000
    ports:
      - 5500:8000
    # wait until 'db' process starts and then run
    depends_on:
      - db

  db:
    image: postgres:12
    # Persist container's '/var/lib/postgresql/data/' in volume named 'sora_postgres'
    volumes:
      - sora_postgres:/var/lib/postgresql/data/
    ports:
      # Allow connecting to container db from localhost:5433
      - 5502:5432
    env_file:
      - .envs/dev.env

volumes:
  # sora_postgres volume (docker will handle local path)
  sora_postgres: